chore(husky): config pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,10 @@
 #!/bin/bash
 
 npm run check:fix
+
+if [ $? -ne 0 ]; then
+  echo "Pre-commit check failed. Please fix the issues and try again."
+  exit 1
+fi  
+
+git add .
